import WelcomePage from "./WelcomePage";
import Login from "./Login";
import Register from "./Register";
import TrainerList from "./TrainerList";
import AdminMember from "./AdminMember";
import AdminMembers from "./AdminMembers";
import PaymentScreen from "./PaymentScreen";
import Reservation from "./Reservation";
import MemberProfile from "./MemberProfile";
import BarcodeScreenExample from "./QrCodeScreen";
export { WelcomePage, Login, Register, TrainerList, AdminMember, AdminMembers, PaymentScreen, Reservation, MemberProfile, BarcodeScreenExample };
